//
// Created by zican on 03.08.22.
//

#ifndef TELEOPERATION_ARCHITECTURE_AHTALKA_JSON_MANAGER_H
#define TELEOPERATION_ARCHITECTURE_AHTALKA_JSON_MANAGER_H

class JSON_manager{
public:


};

#endif //TELEOPERATION_ARCHITECTURE_AHTALKA_JSON_MANAGER_H
